### PR TITLE
Change to use BuildConfig URL

### PR DESCRIPTION
**Pull request by KyletheWolff**
Updated gradle file to have correct url for debug.
Updated RestAdapter endPoint to use gradle url

### CODE REVIEW

**Comment by shekibobo** [comment]
Is this the only place we need this? Does `setEndpoint()` happen anywhere else in the code that needs updating?

**Comment by KyletheWolff** [comment]
ConferenceController.java calls `.setEndpoint("https://conference-schedule-webap.herokuapp.com")` but I figured this was not related.

**Comment by shekibobo** [comment]
I'm wondering if @chenry could weigh in on why that one calls a different API than the rest of them. Is there intent to merge them at some point?

**Comment by chenry** [comment]
yeah....that is the legacy API.  It should be removed at some point, but not part of this task.  Thanks for keeping me honest....hehehehe

**Comment by shekibobo** [comment]
I just bring it up because I was considering this task, and saw that there were a few APIs being used, and I didn't know which one was the official one.

**Comment by chenry** [comment]
Fixes #15

**Pull request merged**
